workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/Runner.ipa
    publishing:
      email:
        recipients:
          - orionspace11@gmail.com